### ISSUE TITLE
"Resource Request Submission Failed"

### ISSUE THREAD

**Issue by SrinivasMushnoori** [vivek-bala/radical.entk-0.6#21]
Terminal output is as follows:

new session: [rp.session.Srinivas-Linux.srinivas.017426.0003]                  \
database   : [mongodb://138.201.86.166:27017/ee_exp_4c]                       ok
create pilot manager                                                          ok
submit 1 pilot(s)
        .                                                                     ok
2017-09-17 11:39:56,491: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2017-09-17 11:39:56,491: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/home/srinivas/VirtualEnvs/EnTK0.6_Env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 237, in run
    self._resource_manager._submit_resource_request()
  File "/home/srinivas/VirtualEnvs/EnTK0.6_Env/local/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 341, in _submit_resource_request
    self._pilot.wait([rp.ACTIVE, rp.FAILED])
AttributeError: 'module' object has no attribute 'ACTIVE'

wait for 1 pilot(s)
                                                                              ok
closing session rp.session.Srinivas-Linux.srinivas.017426.0003                 \
close pilot manager                                                            \
wait for 1 pilot(s)
                                                                         timeout
                                                                              ok
session lifetime: 108.1s                                                      ok
Traceback (most recent call last):
  File "example2.py", line 45, in <module>
    appman.run()
  File "/home/srinivas/VirtualEnvs/EnTK0.6_Env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 465, in run
    raise Error(text=ex)
radical.entk.exceptions.Error: Error: 'module' object has no attribute 'ACTIVE'

Unsure if I should raise this here or on the main RADICAL entk repo.
This is the same error that was encountered on Radical Two on Thursday. Been trying to see if I was doing something wrong for the past two days, but couldn't see what.
Thanks.

**Comment by vivek-bala** [comment]
Run ```export RP_ENABLE_OLD_DEFINES=True``` before running the script. This is due to state name changes

**Comment by SrinivasMushnoori** [comment]
Thanks, I've made a note of it.
