### ISSUE TITLE
shutdown occurs with an error in enqueue thread

### ISSUE THREAD

**Issue by vivek-bala** [vivek-bala/radical.entk-0.6#23]
```
2017-09-27 07:36:41,854: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : ERROR   : Error in enqueue-thread: 
Traceback (most recent call last):
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 320, in _enqueue
    mq_connection.close()
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 688, in close
    self._flush_output(self._closed_result.is_ready)
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 440, in _flush_output
    raise exceptions.ConnectionClosed()
ConnectionClosed

Exception in thread enqueue-thread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/wuh20/virtual-python/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 338, in _enqueue
    raise Error(text=ex)
Error: Error: 
```

This is not consistently reproducible, but does pop up occasionally.

**Comment by vivek-bala** [comment]
This is not really a critical issue. The enqueue thread restarts to resume execution since some object is still present in the RMQ queue.
