### ISSUE TITLE
"Error: Could not detect shell prompt"

### ISSUE THREAD

**Issue by SrinivasMushnoori** [vivek-bala/radical.entk-0.6#31]
Unsure if this is an EnTK/RP issue (if I were to take a guess it looks like a SAGA issue): 

```

        2017-10-10 19:15:03,051: radical.saga.pty    : MainProcess                     : MainThread     : ERROR   : Could not detect shell prompt (ti[0/1869]/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 290, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py $290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
2017-10-10 19:15:03,052: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2017-10-10 19:15:03,052: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 237, in run
    self._resource_manager._submit_resource_request()
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 323, in _submit_resource_req$est
    self._pilot = self._pmgr.submit_pilots(pdesc)
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 432, in submit_pilots
    pilot = ComputePilot(pmgr=self, descr=pd)
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 100, in __init__
    self._resource_sandbox = self._session._get_resource_sandbox(self.as_dict())
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/radical/pilot/session.py", line 936, in _get_resource_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
    interactive=self.interactive)
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 198, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 413, in _initialize_pty
    raise ptye.translate_exception (e)
NoSuccess: Could not detect shell prompt (timeout) (/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py $290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))

2017-10-10 19:15:03,053: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Could not cancel resource request, erro$: 'NoneType' object has no attribute 'cancel'
Traceback (most recent call last):
  File "multiple_exchanges.py", line 101, in <module>
    appman.run()
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 461, in run
    self._resource_manager._cancel_resource_request()
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 374, in _cancel_resource_requ
est
    self._pilot.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'
```

**Comment by vivek-bala** [comment]
Is this still an issue? I believe you resolve this issue by increasing the ssh time out. ```export SAGA_PTY_SSH_TIMEOUT=300```

Please close if this issue is resolved.

**Comment by SrinivasMushnoori** [comment]
Appears resolved.
