### ISSUE TITLE
error installing arch/v0.6

### ISSUE THREAD

**Issue by euhruska** [vivek-bala/radical.entk-0.6#39]
installing  branch arch/v0.6, getting error
```
pip install .
Processing /scratch1/eh22/bw/radical.entk
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-o7nsfvw9-build/setup.py", line 49
        def visit((prefix, strip, found), dirname, names):
                  ^
    SyntaxError: invalid syntax
```

**Comment by andre-merzky** [comment]
Whats the Python and pip version being used here?  Thanks.

**Comment by euhruska** [comment]
python 3.6.3 | packaged by conda-forge
pip 9.0.1            py36h6c6f9ce_4    anaconda

**Comment by andre-merzky** [comment]
I'm afraid we do not yet support python-3, you'll need something like python-2.7.

**Comment by euhruska** [comment]
ah, ok
