### ISSUE TITLE
"Error in enqueue thread"

### ISSUE THREAD

**Issue by SrinivasMushnoori** [vivek-bala/radical.entk-0.6#41]
The following error occurs at the end of the job. Running EnTK in a bag-of-tasks configuration (1 stage, 1 pipeline, N tasks). 

```
2018-01-11 22:25:08,248: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Pipe radical.entk.pipeline.0000 completed
2018-01-11 22:25:08,248: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Active pipes: 0
2018-01-11 22:25:08,248: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
2018-01-11 22:25:08,249: radical.entk.wfprocessor: wfprocessor                     : dequeue-thread : INFO    : Transition of radical.entk.pipeline.0000 to $ew state DONE successful
2018-01-11 22:25:08,249: radical.entk.wfprocessor: wfprocessor                     : MainThread     : INFO    : Terminating enqueue-thread
2018-01-11 22:25:08,250: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : INFO    : Enqueue thread terminated
2018-01-11 22:25:08,251: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : ERROR   : Error in enqueue-thread:
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 320, in _enqueue
    mq_connection.close()
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 688, in close
    self._flush_output(self._closed_result.is_ready)
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 440, in _flush_output
    raise exceptions.ConnectionClosed()
ConnectionClosed

Exception in thread enqueue-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/scm177/VirtualEnvs/EnTK_0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 338, in _enqueue
    raise Error(text=ex)
Error: Error:

2018-01-11 22:25:08,253: radical.entk.wfprocessor: wfprocessor                     : MainThread     : INFO    : Terminating dequeue-thread
2018-01-11 22:25:08,253: radical.entk.wfprocessor: wfprocessor                     : dequeue-thread : INFO    : Terminated dequeue thread
2018-01-11 22:25:08,257: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Terminating synchronizer thread
2018-01-11 22:25:08,258: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Synchronizer thread terminated
2018-01-11 22:25:08,258: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Terminating task manager process
2018-01-11 22:25:09,062: radical.entk.task_manager: MainProcess                     : MainThread     : INFO    : Task manager process closed
2018-01-11 22:25:12,598: radical.entk.task_manager: MainProcess                     : heartbeat      : INFO    : Received heartbeat response
2018-01-11 22:25:12,598: radical.entk.task_manager: MainProcess                     : MainThread     : INFO    : Hearbeat thread terminated
```

My radical-stack is:

```
python               : 2.7.12
  pythonpath           :
  virtualenv           : /home/scm177/VirtualEnvs/EnTK_0.6_env

  radical.analytics    : v0.45.2-7-g6862da3@devel
  radical.pilot        : 0.46.2
  radical.utils        : 0.46.2
  saga                 : 0.46.1

```

**Comment by vivek-bala** [comment]
This is just the enqueue thread restarting and resuming termination. Does this terminate any of your tasks in the pipeline?

**Comment by vivek-bala** [comment]
Bump. Please test again. If this is not an issue any more, please close the ticket.

**Comment by vivek-bala** [comment]
Hey @SrinivasMushnoori, if you don't see this issue any more, please close this ticket.

**Comment by SrinivasMushnoori** [comment]
Apologies, I missed this. I'll test again and let you know.

**Comment by SrinivasMushnoori** [comment]
I still see this. The error is slightly different this time around:

```
2018-03-03 00:50:00,285: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Found parent pipeline: radical.entk.pipeline.0000
2018-03-03 00:50:00,287: radical.entk.wfprocessor.0000: wfprocessor                     : dequeue-thread : INFO    : Transition of radical.entk.stage.0001 to new state DONE successful
2018-03-03 00:50:00,290: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : ERROR   : Transition of radical.entk.stage.0002 to SCHEDULING state failed, error: (-1, "error(32, 'Broken pipe')")
2018-03-03 00:50:00,290: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : ERROR   : Error while updating stage state, rolling back. Error:
2018-03-03 00:50:00,291: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : ERROR   : Transition of radical.entk.stage.0002 to DESCRIBED state failed, error:
2018-03-03 00:50:00,292: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : ERROR   : Error in enqueue-thread:
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 418, in _enqueue
    logger=self._logger)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/utils/init_transition.py", line 40, in transition
    local_prof = profiler)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/utils/sync_initiator.py", line 25, in sync_with_master
    correlation_id = corr_id
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_publish
    mandatory, immediate)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2163, in publish
    immediate=immediate)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/pika/channel.py", line 415, in basic_publish
    raise exceptions.ChannelClosed()
ChannelClosed

Exception in thread enqueue-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 441, in _enqueue
    raise Error(text=ex)
Error: Error:

2018-03-03 00:50:00,302: radical.entk.wfprocessor.0000: wfprocessor                     : MainThread     : INFO    : Starting enqueue-thread
2018-03-03 00:50:00,304: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : enqueue-thread started
2018-03-03 00:50:00,339: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received radical.entk.stage.0002 with state SCHEDULING
2018-03-03 00:50:00,339: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Found parent pipeline: radical.entk.pipeline.0000
2018-03-03 00:50:00,340: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Transition of radical.entk.stage.0002 to new state SCHEDULING successful
```

**Comment by vivek-bala** [comment]
The RabbitMQ channel seems to be closed. Can you check if the instance is up on the host?

**Comment by SrinivasMushnoori** [comment]
As far as I can tell, yes. I do a `docker ps` and I can see my rmq instance. 
Unsure if by "host" you mean the remote resource? If you do mean the remote resource, how do I check if the instance is up?

**Comment by vivek-bala** [comment]
Hey Srinivas, based on our discussions I am assuming you don't face this issue any more. Please do reopen (in the new repo) if this issue pops up again.

**Comment by SrinivasMushnoori** [comment]
Hi, unfortunately I will have to reopen this ticket because I still see it (however it's dequeue thread this time):
```
2018-04-18 21:39:34,922: radical.entk.wfprocessor.0010: wfprocessor                     : enqueue-thread : INFO    : Enqueue thread terminated
2018-04-18 21:39:34,922: radical.entk.wfprocessor.0010: wfprocessor                     : dequeue-thread : ERROR   : Unable to receive message from completed queue: 
2018-04-18 21:39:34,923: radical.entk.wfprocessor.0010: wfprocessor                     : dequeue-thread : ERROR   : Error in dequeue-thread: 
2018-04-18 21:39:34,923: radical.entk.wfprocessor.0010: wfprocessor                     : MainThread     : INFO    : Terminating dequeue-thread
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 472, in _dequeue
    method_frame, header_frame, body = mq_channel.basic_get(queue=self._completed_queue[0])
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2032, in basic_get
    no_ack=no_ack)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/pika/channel.py", line 360, in basic_get
    self._validate_channel_and_callback(callback)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/pika/channel.py", line 1362, in _validate_channel_and_callback
    raise exceptions.ChannelClosed()
ChannelClosed

Exception in thread dequeue-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 592, in _dequeue
    raise Error(text=ex)
Error: Error: 

2018-04-18 21:39:35,013: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating synchronizer thread
2018-04-18 21:39:35,014: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Synchronizer thread terminated
```

Will upload logs shortly.

**Comment by vivek-bala** [comment]
Is this the error during termination or during execution? If it is during termination, please ignore this for now.

**Comment by SrinivasMushnoori** [comment]
This seems to be right before termination.

**Comment by vivek-bala** [comment]
Can you paste the entire verbose log (and not just the tail)?

**Comment by SrinivasMushnoori** [comment]
I will, the next time it occurs. It is inconsistent.

**Comment by SrinivasMushnoori** [comment]
This does not occur with the latest release.
